In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,101,2)  # Start, stop, step size

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((2,3)) # tuple indicates 2 rows by 3 colums

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((3,3)) # tuple indicates 3 rows by 3 columns of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0,5,10)  # 10 evenly spaced points between 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4) # identity matrix - linear algebra problems 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5)  # random samples in a uniform distribution

array([0.29883325, 0.06669328, 0.77803733, 0.58386189, 0.24705162])

In [21]:
np.random.randn(2,3) # return numbers in a standard normal distribution

array([[ 0.65595197,  1.11997767, -0.67744907],
       [ 0.85830178,  0.70987762, -0.28834237]])

In [23]:
np.random.randint(1,100,3)

array([57, 74, 49])

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)

In [28]:
ranarr

array([11,  2, 21, 19, 35,  0, 39, 14, 16,  0])

In [31]:
arr.reshape(5,5)  # reshape the array to x by y - must fill evenly

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr.max()   # max value of the array

39

In [34]:
ranarr.min()   # min value of the array 

0

In [35]:
ranarr.argmax() # location in the array of the max value (argmin for min)

6

In [37]:
arr.shape   # 1 dimensional vector

(25,)

In [38]:
arr = arr.reshape(5,5)

In [39]:
arr.shape

(5, 5)

In [40]:
arr.dtype  # data type in the array

dtype('int64')

In [42]:
from numpy.random import randint

In [44]:
randint(2,10)

5