In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [8]:
arr[1:5]

array([1, 2, 3, 4])

In [15]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [18]:
arr[0:5] = 100  # broadcast the original values from 0 to 4 now as 100

In [19]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [21]:
arr = np.arange(0,11)  # reset to original vaues

In [23]:
slice_of_arr = arr[0:6]  # create a reference to arr[0:6]

In [24]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [25]:
slice_of_arr[:] = 99  # this will change the original! 

In [40]:
arr # this is to avoid memory issues with very large arrays
    # also to make it easier to change sections 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [34]:
arr_copy = arr.copy()  # you must signify you want to copy an array

In [36]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [37]:
arr_copy[:] = 100

In [38]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [39]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [41]:
# 2d array

In [42]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [43]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [47]:
arr_2d[0][0]  # return [row][column]

5

In [48]:
arr_2d[0,0]   # same as above, but single bracket

5

In [49]:
arr_2d[0]  # pull a row

array([ 5, 10, 15])

In [50]:
# use slice notation to grab a section of the array/matrix

In [52]:
arr_2d[:2,1:]    # grab rows 0 and 1 in [:2, 
                 # grab columns 1 and 2 in 1:]

array([[10, 15],
       [25, 30]])

In [54]:
arr_2d[1:3,:2]

array([[20, 25],
       [35, 40]])

In [55]:
arr = np.arange(1,11)

In [56]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr > 5    # conditional selection

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [58]:
bool_arr = arr > 5

In [60]:
arr[bool_arr]  # returns only the true values from the original array

array([ 6,  7,  8,  9, 10])

In [63]:
arr[arr<3]   # can use conditional selection within []

array([1, 2])

In [64]:
arr_2d = np.arange(50).reshape(5,10)

In [65]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [66]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])